apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s4dxkvo8g-nodejs-gitops
  description: This is GitOps manifest for s4dxkvo8g-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=s4dxkvo8g-nodejs
    backstage.io/kubernetes-id: s4dxkvo8g-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s4dxkvo8g-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s4dxkvo8g-nodejs
